name: Manual Workflow

on: 
  workflow_dispatch:
env:
  a: ${{vars.a}}  
  b: ${{vars.b}}      
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
  test:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Print test
      run: |
        echo "Job1 Test"
    - uses: actions/checkout@v2
    - name: Executer le script si la condition est remplie
      if: (vars.a > 0) && (vars.b > 0)
      run: |
        echo "La valeur de la variable a est : ${{ vars.a }}"
        echo "La valeur de la variable b est : ${{ vars.b }}"
 
  jobs2 :
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: pip install numpy
      run: pip install numpy
    - name: install pandas
      run: pip install pandas

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  

    - name: Execute Python script
      run: python script.py




   
