name: Manual Workflow

on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
  test:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Print test
      run: |
        echo "Job Test"

  deploy:
    runs-on: ubuntu-latest

    if: (vars.A > 0) && (vars.B > 0)

    steps:
        - uses: actions/checkout@v2
        - name: Executer un script si la condition remplie
          run: |
            echo "La valeur de la variable a est : ${{ vars.A }}"
            echo "La valeur de la variable b est : ${{ vars.B }}"
  jobs2 :
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  

    - name: Execute Python script
      run: python app.py


            # echo "La valeur de la variable a * b est : ${{ vars.A* vars.B }}"
            # echo "La valeur de la variable a + b est : ${{ vars.A + vars.B }}"

   
